### ISSUE TITLE
Feature Request: Inputs in predefined messages (maybe basic control-flow?)

### ISSUE THREAD

**Issue by stites** [smallhadroncollider/cmt#1]
Hi @smallhadroncollider, wonderful project!

I would love the ability to use inputs in predefined messages. I think it would add quite a bit of flexibility but I wanted to see if you would be interested in a feature like this and I think it's important to point out that, in my head, this gets a bit weird when defining multiline predefines. The motivating example would be a template like the following:

```
{
    "Subproject" = [ "ghc", "cabal"]
    "SpecificThing" = @
}
{
    vb = "[${Subproject}] version bump"
}

[${Subproject}] ${SpecificThing}: ${*}
```

The unmotivating example which shows how this feature can get weird / be abused:
```
{
    "Subproject" = [ "ghc", "cabal"]
    "Body" = !@
    "Footer" = !@
}
{
    multiline1 = "[${Subproject}] ${*}

                  ${Body}"

    multiline2 = "[${Subproject}] ${*}
                  ${Body}
           not only is there weird spacing
               but no one noticed and now it's already in git history
                          ${Footer}"
}

[${Subproject}] ${SpecificThing}: ${*}
```

I'd be happy to implement this myself if we can work out the kinks!

As an aside, I think you could also achieve the same thing with the addition of basic control flow structures (and maybe recursively-nested inputs) but my examples all look horrible.

**Comment by smallhadroncollider** [comment]
I don't see why not. But I'm fairly new to this whole parsing lark.

I'm currently looking into adding character limits (just worked out how to get that working with `getChar`), repeated sections, free-text option in lists, and additional descriptions, which I'm imagining will look like the following:

```cfg
# Input parts
{
    # items with descriptions
    {"Type", "What sort of change?"} = [
        {"feat", "A feature"},
        {"fix", "A fix"},
        {"docs", "The docs"},
        {"style", "Style changes"},
        {"refactor", "A refactoring"},
        {"test", "Tests"},
        {"chore", "Boring stuff"},
       { @, "Other"} # free-text option
    ]

    # repeated input
    [
        "Co-Author Name": @
        "Co-Author Email": @
    ]

    # description
    {"Scope", "What's changed?"} = %

    # limit to 50 characters
    "Short Message" = @[50]

    # limit each line to 72 characters
    "Body" = !@[72]
}

# Output format
${Type} (${Scope}): ${Short Message}

$[Co-Author: ${Co-Author Name} ${Co-Author Email}]

${Body}
```

I don't think your suggestion would clash with any of those.
