### ISSUE TITLE
Upload this to homebrew

### ISSUE THREAD

**Issue by mochadwi** [smallhadroncollider/cmt#3]
It will be awesome if we can install this great pre-defined commit message to homebrew

**Comment by smallhadroncollider** [comment]
I can't submit it myself, so someone else will need to do the pull request to Homebrew.

I'm happy to generate the recipe file and then guide you through the submission process if you are willing. It might not be for a few weeks as I'm on paternity leave, but will hopefully be able to find a time soon.

**Comment by smallhadroncollider** [comment]
Sorry, I didn't see your hooray emoticon, so never responded!

I'm just testing a formula now.

**Comment by smallhadroncollider** [comment]
```ruby
require "language/haskell"

class Cmt < Formula
  include Language::Haskell::Cabal

  desc "Write consistent git commit messages based on a custom template"
  homepage "https://github.com/smallhadroncollider/cmt"
  url "https://github.com/smallhadroncollider/cmt/archive/0.7.0.tar.gz"
  sha256 "4bfaec12f3169f11d334313b6ae725ad7cda0d985e197738f0cad2074cd3920e"

  depends_on "cabal-install" => :build
  depends_on "ghc" => :build
  depends_on "hpack" => :build

  def install
    system "hpack"
    install_cabal_package
  end

  test do
    (testpath/".cmt").write <<~EOS
      {}

      ${*}
    EOS

    expected = <<~EOS
      *** Result ***

      Blah blah blah


      run: cmt --prev to commit

    EOS

    assert_match expected, shell_output("#{bin}/cmt --dry-run 'Blah blah blah' | sed $'s,\x1b\\[[0-9;]*[a-zA-Z],,g'")
  end
end
```

**Comment by smallhadroncollider** [comment]
You'll need to:

1) fork [homebrew-core](https://github.com/Homebrew/homebrew-core)
2) add the above code to a file called `cmt.rb` in the `Formula` directory
3) do a git commit with the message `cmt 0.7.0`
4) push to your fork
5) submit a pull request to homebrew-core repo

**Comment by smallhadroncollider** [comment]
If you let me know when you've done that I can jump in on the PR conversation and help with any issues.

**Comment by smallhadroncollider** [comment]
(Just updated the code above to have latest version)

**Comment by kahlil29** [comment]
@smallhadroncollider  I'm willing to do this. Can I assign myself and with the above steps, submit the PR?

**Comment by smallhadroncollider** [comment]
@kahlil29 Sure, that would be great. Thanks!

**Comment by kahlil29** [comment]
I think the version number in the commit should be `0.7.1` as that is the latest version, right?

**Comment by kahlil29** [comment]
I've opened a PR (with all the steps done correctly, I hope) at https://github.com/Homebrew/homebrew-core/pull/49486 

Fingers crossed 🤞  

Also, great tool! Thanks for this lovely contribution to the community 😄

**Comment by smallhadroncollider** [comment]
@kahlil29 Amazing. Thanks!

**Comment by kahlil29** [comment]
The PR has been merged 🎉 
I think this issue can be closed now. 
Thanks for your help with this @smallhadroncollider  😄

**Comment by smallhadroncollider** [comment]
Thank you @kahlil29!
