### ISSUE TITLE
Consider unmarking tarballs as prerelease?

### ISSUE THREAD

**Issue by mitchblank** [smallhadroncollider/cmt#9]
Homebrew currently is refusing to bottle this package for installation because of a new `audit` check that was added since the last release:
```
$ brew audit --strict --online cmt
cmt:
  * 0.7.1 is a GitHub pre-release.
Error: 1 problem in 1 formula detected
```

Homebrew has the ability to whitelist particular "prerelease" versions but I thought I'd ask first if you'd be willing to change the tagging policy first.

The basic problem is that people use "prerelease" to mean two separate things:
* Versions prior to some future "1.0.0" release
* Versions like "1.2.3rc1" where the particular release is "prerelease" but the project in general is not

Homebrew guesses that it means the second one.  Since they do got generally want PRs that "upgrade" to alpha/beta/RC versions they reject via `brew audit` any github "prerelease" versions.

In the case of `cmt` where *all* of the releases are "pre" this causes problems though.

I would recommend unmarking the "prerelease" flag on these releases.  The version number is "0.x" which indicates that it's "pre-1.0" well enough.

**Comment by smallhadroncollider** [comment]
Thanks for letting me know. I think you’re right. Should be sorted now.
